### ISSUE TITLE
What is the purpose of scaling the input image to -0.5 to 1.5

### ISSUE THREAD

**Issue by fxlong** [princeton-vl/DPVO#17]
image = 2 * (image[None,None] / 255.0) - 0.5

**Comment by RohanChacko** [comment]
Same question.

**Comment by lahavlipson** [comment]
This was a mistake; we intended to scale to [-1, 1], but by the time we had noticed, we had already trained a model using [-0.5, 1.5] so we left it in. This shouldn't impact the performance.
