### ISSUE TITLE
Is it possible to support panoramic images?

### ISSUE THREAD

**Issue by CanCanZeng** [princeton-vl/DPVO#3]
Hi, is it possible for DPVO to support panoramic images? The camera model of panoramic image is not like pinhole camera but equirectangular camera model, see here https://wiki.panotools.org/Equirectangular_Projection

**Comment by zachteed** [comment]
Hi, at the moment only linear cameras (or cameras that can be rectified) are supported. I would like to add functionality for more general cameras at some point but currently it won't work on panoramic video

**Comment by CanCanZeng** [comment]
Thanks for your kind reply and look forward to your future work
