### ISSUE TITLE
DPRetrieval Installation Error

### ISSUE THREAD

**Issue by FaSch87** [princeton-vl/DPVO#64]
Hi, thanks for the upgrade of your amazing work!
I faced an issue when trying to install the image retrieval with `pip install ./DPRetrieval`:
`ERROR: Invalid requirement: './DPRetrieval': Expected package name at the start of dependency specifier
    ./DPRetrieval
    ^
Hint: It looks like a path. File './DPRetrieval' does not exist.`

Installation of DBoW2 has worked. Am I missing something?

**Comment by Dong09** [comment]
the same error. But it doesn't seem to be getting in the way

**Comment by lahavlipson** [comment]
Sorry about that, I forgot to include DPRetrieval in the most recent commit. It's now there.
