### ISSUE TITLE
Monocular Depth and DPVO (Metric3D + Unidepth)

### ISSUE THREAD

**Issue by pablovela5620** [princeton-vl/DPVO#70]
I noticed in the `Limitations` Section of the DPVSlam paper monocular depth estimators are mentioned

> DPV-SLAM, like most monocular systems, sometimes suffers from scale-drift in outdoor environments, though orthogonal work has addressed this problem using monocular depth networks [[47](https://arxiv.org/html/2408.01654v1#bib.bib47)].

Have you all looked into using [Metric3D](https://github.com/YvanYin/Metric3D) or [Unidepth](https://github.com/lpiccinelli-eth/UniDepth) for DPVSlam? In particular Unidepth looks interesting because it also provides estimates for camera intrinsic. I've seen that Metric3D has been done for DROID slam but I'm curious to see how it would work for sparse points like DPVSlam

**Comment by lahavlipson** [comment]
Using Unidepth for camera intrinsics and as a depth prior sounds like a good idea. However, the intrinsic estimates could vary significantly from frame-to-frame, especially for images taken with a large focal length. This might cause issues with the estimated camera positions. So the jury is out

**Comment by pablovela5620** [comment]
> Using Unidepth for camera intrinsics and as a depth prior sounds like a good idea. However, the intrinsic estimates could vary significantly from frame-to-frame, especially for images taken with a large focal length. This might cause issues with the estimated camera positions. So the jury is out

Agreed! I was thinking using an average of the first 8 frames similar to how there's an initialization for DPVO, but this could still lead to some instability. There's been another development via [GeoCalib](https://github.com/cvg/GeoCalib) that allows using multi frames (and not necessarily in a sequence) to estimate intrinsic, which can then be used. I guess it depends on what the usecase you all imagine for DPVO/DPVSlam. If all frames will be available ahead of time (for example when using a video) or if slam will be performed incrementally and online.

I made a [hugging face demo (https://huggingface.co/spaces/pablovela5620/MiniDPVO?logs=container) that uses Dust3r to estimate intrinsic on the first frame of a video, at some point I'll see if Multiframe GeoCalib or UniDepth would result in a better results.

I am very interested to see if metrically accurate slam could be done with a combination of DPVSlam + Metric Depth Estimator

**Comment by lbblz** [comment]
> > 使用Unidepth作为相机内在和深度之前听起来是个好主意。然而，内在估计值可能因帧而异，特别是对于以大焦距拍摄的图像。这可能会导致估计的相机位置出现问题。所以陪审团出局了
> 
> 同意！我正在考虑使用前8帧的平均值，类似于DPVO的初始化方式，但这仍然可能导致一些不稳定。通过[GeoCalib](https://github.com/cvg/GeoCalib)进行了另一项开发，允许使用多帧（不一定是序列）来估计内在，然后可以使用。我猜这取决于你们想象到的DPVO/DPVSlam的用例是什么。如果所有帧都提前可用（例如在使用视频时），或者如果快速和在线逐步执行。
> 
> 我做了一个[拥抱脸演示](https://huggingface.co/spaces/pablovela5620/MiniDPVO?logs=container)，使用Dust3r来估计视频第一帧的内在，在某个时候，我会看看多帧GeoCalib或UniDepth是否会产生更好的结果。
> 
> 我非常有兴趣看看是否可以通过DPVSlam + Metric Depth Estimator的组合来完成公制准确的大满贯

Hi, have you implemented this, and if so, could you tell me the details

**Comment by lbblz** [comment]
> > 使用Unidepth作为相机在和深度之前听起来是个好主意。然而，内在估计值可能因帧而异，特别是对以大焦距拍摄的图像。这可能会导致估计的相机位置出现问题。所以陪审团出局了
> 
> 同意！我正在考虑使用前8帧的平均值，类似于DPVO的初始化方式，但这仍然可能导致一些不稳定。通过[GeoCalib](https://github.com/cvg/GeoCalib)进行了另一项开发，允许使用多帧（不一定是序列）来估计内在，然后可以使用。我猜这取决于你们想象到的DPVO/DPVSlam的用例是什么。如果所有帧都提前可用（例如使用视频时），或者如果快速和在线逐步执行。
> 
> 我做了一个[拥抱脸演示](https://huggingface.co/spaces/pablovela5620/MiniDPVO?logs=container)，使用Dust3来估计视频第一帧的内在，在某个时候，我会看看多帧GeoCalib或UniDepth是否会产生更好的结果。
> 
> 我非常有兴趣看看是否可以通过DPVSlam + Metric Depth Estimator的组合来完成公制准确的大满贯



> > Using Unidepth for camera intrinsics and as a depth prior sounds like a good idea. However, the intrinsic estimates could vary significantly from frame-to-frame, especially for images taken with a large focal length. This might cause issues with the estimated camera positions. So the jury is out
> 
> Agreed! I was thinking using an average of the first 8 frames similar to how there's an initialization for DPVO, but this could still lead to some instability. There's been another development via [GeoCalib](https://github.com/cvg/GeoCalib) that allows using multi frames (and not necessarily in a sequence) to estimate intrinsic, which can then be used. I guess it depends on what the usecase you all imagine for DPVO/DPVSlam. If all frames will be available ahead of time (for example when using a video) or if slam will be performed incrementally and online.
> 
> I made a [hugging face demo](https://huggingface.co/spaces/pablovela5620/MiniDPVO?logs=container) that uses Dust3r to estimate intrinsic on the first frame of a video, at some point I'll see if Multiframe GeoCalib or UniDepth would result in a better results.
> 
> I am very interested to see if metrically accurate slam could be done with a combination of DPVSlam + Metric Depth Estimator

Hi, have you implemented this. and if so, could you tell me the details。
 DPVSlam + Metric Depth Estimator

**Comment by pablovela5620** [comment]
I have not implemented this unfortunately

**Comment by HESoldierRO** [comment]
> I have not implemented this unfortunately

I found that there was a work named https://github.com/Jianxff/droid_metric, combind [DROID-SLAM](https://github.com/princeton-vl/DROID-SLAM) and [Metric3D](https://github.com/YvanYin/Metric3D), taking metric depth to improve the performance of DROID-SLAM in monocular mode.
