### ISSUE TITLE
Wrong pointcloud color shown in colmap gui

### ISSUE THREAD

**Issue by blackjacket996** [princeton-vl/DPVO#74]
Hey! I successfully run demo.py --save_colmap and got three files: camera.txt, points3D.txt and images.txt. I wanna show them using colmap gui, and I got a pointcloud with right shape but wrong color.image above is the origin image and the other is the model shown in colmap. Look at the blocks on the ground, there are no purple and orange blocks in the image. And I also try six different combinations of the "RGB" data in the points3D.txt file generated by the demo.py, but none of the combinations  is correct.
![000001](https://github.com/user-attachments/assets/248dcd52-00ab-478a-9c20-47fb9d361f56)
![Screenshot from 2024-09-06 10-46-01](https://github.com/user-attachments/assets/de1639a4-8866-46f3-b7cd-031776681e8b)

**Comment by blackjacket996** [comment]
I've solved the problem by rewrite the line 50-52 of plot_utils.py:
```
for i, ((x, y, z),(r,g,b) in enumrate(zip((points*scale).tolist(), colors)):
       points3D += f"{x} {y} {z} {r} {g} {b}` + "0.0 0 0 0 0 0 0\n"
```

**Comment by lahavlipson** [comment]
Thanks for raising this issue. It seems that your code change skips the "POINT3D_ID" for each line (see [doc](https://colmap.github.io/format.html#points3d-txt)). Without it, colmap seems to crash for me with `Check failed: points3D_.emplace(point3D_id, std::move(point3D)).second`. For reference, I am using COLMAP 3.10-dev

**Comment by blackjacket996** [comment]
Sry, I miss the param "i“, it should be:
```
for i, ((x, y, z),(r,g,b) in enumrate(zip((points*scale).tolist(), colors)):
       points3D += f"{i} {x} {y} {z} {r} {g} {b}" + "0.0 0 0 0 0 0 0\n"
```
