### ISSUE TITLE
About distributed training

### ISSUE THREAD

**Issue by doujiarui** [princeton-vl/DPVO#79]
If I have multiple GPUs, how do I implement distributed computing? I implemented a version myself, but the time to use 4 GPU 4090 is less than half the time to use 1 GPU, is this normal?

The related libraries I use are as follows:
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP

Have you done distributed training, and what's the impact compared to single GPU training?

**Comment by markinruc** [comment]
@Nemophilist98 Hi, have you solved the problem? I wonder how to implement distributed training. Thanks!
