### ISSUE TITLE
Warning BA failed

### ISSUE THREAD

**Issue by Davidyao99** [princeton-vl/DPVO#84]
The bundle adjustment is failing and throwing the following exception:

![image](https://github.com/user-attachments/assets/1954113c-dbdb-4033-b380-99228deda590)

Anyone have similar experience? I did not change any of the internals and dpvo setup built successfully. Any help or insight is much appreciated. Thank you!

**Comment by lahavlipson** [comment]
From the function signature, it looks like the dpvo binaries were installed from a previous version of the code. 

Try: `pip uninstall dpvo && pip install .`

**Comment by Davidyao99** [comment]
I did that but I seem to be facing the same error. Is there a way to check that my built version is the latest?

**Comment by lahavlipson** [comment]
If the latest c++/cuda kernels are installed, the function signature you see when running `>>> import torch; import cuda_ba; help(cuda_ba.forward)` should be:
```
forward(...) method of builtins.PyCapsule instance
    forward(arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor, arg4: torch.Tensor, arg5: torch.Tensor, arg6: torch.Tensor, arg7: torch.Tensor, arg8: torch.Tensor, arg9: int, arg10: int, arg11: int, arg12: int, arg13: bool) -> List[torch.Tensor]
```
which matches the function signature:
https://github.com/princeton-vl/DPVO/blob/859bbbfdac6c6185f345003b3c473901fcd13ace/dpvo/fastba/ba.cpp#L32

Maybe delete the `build/` folder and `.egg` files before reinstalling if you haven't tried that.

**Comment by Davidyao99** [comment]
I see I see, thank you so much. I managed to resolve it by recreating a new environment and reinstalling the repo.
